[build]
  command = "echo 'No build needed'"
  functions = "netlify/functions"
  publish = "netlify/public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/search"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.11"

[functions]
  included_files = ["netlify/functions/**"]

